version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 2
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      npm:
        patterns:
          - "*"

  # Enable version updates for pip
  - package-ecosystem: "pip"
    directories:
      - "/api"
      - "/client"
      - "/plugins/evidence"
      - "/plugins/sentinel"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      pip:
        patterns:
          - "*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      github-actions:
        patterns:
          - "*"
