[project]
name = "tsx-user-status"
version = "0.1.0"
description = "Status for users"
authors = [
    { name = "Kevin Issa", email = "kevin.issa@truesec.se" }
]
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
]

[tool.poetry.dependencies]
howler-api = { path = "../../cccs/api", develop = true }

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
select = [
    "E",
    "F",
    "W",
    "C901",
    "I",
    "N",
    "D1",
    "D2",
    "ANN",
    "S",
    "T20",
    "PIE",
    "FLY",
    "TRY",
]
ignore = [
    "ANN003",
    "ANN201",
    "ANN401",
    "D100",
    "D104",
    "D105",
    "D107",
    "D203",
    "D213",
    "N818",
    "S603",
    "TRY003",
    "TRY300",
]

[tool.ruff.lint.per-file-ignores]
"test/**" = ["D", "ANN", "S", "N818", "TRY", "PIE", "E402"]

[tool.ruff.lint.flake8-annotations]
ignore-fully-untyped = true
mypy-init-return = true

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ruff (>=0.15.11,<0.16.0)"
]
