{{- $hasCerts := false -}}
{{- range .Values.rest.datastore.hosts -}}
  {{- if .cert -}}
    {{- $hasCerts = true -}}
  {{- end -}}
{{- end -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.rest.name }}-correlation"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: correlation
{{ include "howler.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/version: {{ .Chart.AppVersion }}
      app.kubernetes.io/name: {{ include "howler.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/name: {{ include "howler.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: correlation
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      nodeSelector:
{{ toYaml .Values.rest.nodeSelector | indent 8 }}
      affinity:
{{ toYaml .Values.rest.affinity | indent 8 }}
      tolerations:
{{ toYaml .Values.rest.tolerations | indent 8 }}
      containers:
      - name: {{ include "howler.name" . }}
        securityContext:
          {{- toYaml .Values.rest.securityContext | nindent 12 }}
        image: "{{ .Values.images.rest.repository }}:{{ .Values.images.rest.tag }}"
        imagePullPolicy: {{ .Values.images.rest.pullPolicy | quote }}
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: conf
          mountPath: /etc/howler/conf/
        {{- if $hasCerts }}
        - name: howler-certs
          mountPath: /etc/howler/certs/
        {{- end }}
        env:
        {{include "sharedEnv" . | indent 8}}
        - name: WORKERS
          value: "4"
        - name: HWL_USE_REST_API
          value: "false"
        - name: HWL_USE_WEBSOCKET_API
          value: "false"
        - name: HWL_USE_JOB_SYSTEM
          value: "true"
        - name: HWL_ENABLE_CORRELATIONS
          value: "true"
        - name: APP_NAME
          value: {{ .Values.rest.appName | default "howler" }}
        resources:
          {{- toYaml .Values.rest.resources | nindent 12 }}
      volumes:
      - name: conf
        configMap:
          name: howler-server-conf
      {{- if $hasCerts }}
      - name: howler-certs
        secret:
          secretName: howler-certs
      {{- end }}
