apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.howlerRest.name }}-correlation"
  labels:
    app.kubernetes.io/component: correlation
{{ include "howler.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/version: {{ .Chart.AppVersion }}
      app.kubernetes.io/name: {{ include "howler.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/name: {{ include "howler.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: correlation
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      nodeSelector:
{{ toYaml .Values.howlerRest.nodeSelector | indent 8 }}
      affinity:
{{ toYaml .Values.howlerRest.affinity | indent 8 }}
      tolerations:
{{ toYaml .Values.howlerRest.tolerations | indent 8 }}
      containers:
      - name: {{ include "howler.name" . }}
        image: "{{ .Values.howlerRest.image.repository }}:{{ .Values.howlerRest.image.tag }}"
        imagePullPolicy: {{ .Values.howlerRest.image.pullPolicy | quote }}
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: conf
          mountPath: /etc/howler/conf/
        env:
        {{include "sharedEnv" . | indent 8}}
        - name: HWL_USE_REST_API
          value: "false"
        - name: HWL_USE_WEBSOCKET_API
          value: "false"
        - name: HWL_USE_JOB_SYSTEM
          value: "true"
        - name: APP_NAME
          value: {{ .Values.howlerRest.appName | default "howler" }}
        resources:
          {{- toYaml .Values.howlerRest.resources | nindent 12 }}
      volumes:
      - name: conf
        configMap:
          name: howler-server-conf
