apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  type: NodePort
  ports:
    - port: 30200
      targetPort: 30200
      nodePort: 30200
      protocol: TCP
  selector:
    app: elasticsearch
