{{- if .Values.ingress.enabled -}}
{{- $fullName := include "howler.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "howler.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.rest.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-rest
                port:
                  name: rest
          - path: {{ .Values.ingress.websocket.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-rest-websocket
                port:
                  name: websocket
          - path: {{ $.Values.ingress.ui.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-web
                port:
                  name: web
{{- end }}
