apiVersion: v1
kind: Service
metadata:
  name: howler-rest
  namespace: {{ .Release.Namespace }}
  labels:
    app: howler-rest
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.rest.port | default 5000 }}
      targetPort: 5000
      protocol: TCP
      name: rest
  selector:
    app.kubernetes.io/name: {{ include "howler.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: rest
