apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.howlerUi.name }}
  labels:
    app.kubernetes.io/component: ui
{{ include "howler.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/version: {{ .Chart.AppVersion }}
      app.kubernetes.io/name: {{ include "howler.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: ui
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/name: {{ include "howler.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      nodeSelector:
{{ toYaml .Values.howlerUi.nodeSelector | indent 8 }}
      affinity:
{{ toYaml .Values.howlerUi.affinity | indent 8 }}
      tolerations:
{{ toYaml .Values.howlerUi.tolerations | indent 8 }}
      containers:
      - name: {{ include "howler.name" . }}
        image: "{{ .Values.howlerUi.image.repository }}:{{ .Values.howlerUi.image.tag }}"
        imagePullPolicy: {{ .Values.howlerUi.image.pullPolicy | quote }}
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_HOWLER_API
          value: "REST"
        resources:
          {{- toYaml .Values.howlerUi.resources | nindent 12 }}
