"""
Dev environment setup for the Howler MCP server.

Mirrors the purpose of api/howler/odm/random_data.py — a single script
that bootstraps everything needed for local development.

What it does:
  1. Writes a .env file (read by docker compose up automatically).
  2. Prints export commands for shell setup.
  3. Optionally verifies that Keycloak is reachable.
  4. Optionally fetches a bearer token from Keycloak and injects it into
     .vscode/mcp.json so VS Code can authenticate immediately (no prompts).

Usage:
  python3 dev_setup.py              # write .env, print exports
  python3 dev_setup.py --verify     # also verify Keycloak connectivity
  python3 dev_setup.py --token      # also fetch token and update mcp.json
  python3 dev_setup.py --start      # do all above, then start the MCP server
"""

import argparse
import json
import os
import signal
import subprocess
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

# ── Dev defaults ─────────────────────────────────────────────────────────────
# Change these only if your local setup differs from the standard
# docker-compose dev stack (api/dev/docker-compose.yml).

DEV_ENV: dict[str, str] = {
    # Howler API — the Flask backend, NOT the MCP server itself.
    "HOWLER_API_VERSION": "v1",
    "HOWLER_API_HOST": "localhost",
    "HOWLER_API_PORT": "3000",
    "HOWLER_API_BASE_URL": "http://localhost:3000/api/v1",
    "HOWLER_API_AUDIENCE": "howler",
    "HOWLER_API_SCOPE": "howler",
    "HOWLER_API_TIMEOUT": "5.0",
    # Keycloak — must match the realm configured in api/dev/keycloak/keycloak-realm.json.
    "AUTH_HOST": "localhost",
    "AUTH_PORT": "9100",
    "AUTH_REALM": "HogwartsMini",
    "AUTH_CLIENT_ID": "howlermcp",
    # howlermcp is a public client — no secret is required for PKCE/auth-code flow.
    # AUTH_CLIENT_SECRET is intentionally left unset; docker compose will warn but work.
    "AUTH_TOKEN_URL": "http://localhost:9100/realms/HogwartsMini/protocol/openid-connect/token",
    "AUTH_JWKS_URI": "http://localhost:9100/realms/HogwartsMini/protocol/openid-connect/certs",
    "AUTH_ISSUER": "http://localhost:9100/realms/HogwartsMini",
    "AUTH_AS_SERVER_URL": "http://localhost:9100/realms/HogwartsMini",
    # MCP server — where the server binds and what it advertises to clients.
    "MCP_HOST": "0.0.0.0",
    "MCP_PUBLIC_HOST": "localhost",
    "MCP_PORT": "8000",
    "MCP_BASE_URL": "http://localhost:8000/mcp",
    "MCP_SCOPE": "howlermcp:access",
    "MCP_AUDIENCE": "howlermcp",
}

# Dev credentials for the token verification step.
_TEST_USER = "goose"
_TEST_PASS = "goose"


def write_env_file(path: Path) -> None:
    """Write all dev env vars to a .env file for docker compose."""
    lines = ["# Auto-generated by dev_setup.py — DO NOT COMMIT\n"]
    for key, value in DEV_ENV.items():
        lines.append(f"{key}={value}\n")
    path.write_text("".join(lines))
    print(f"  Wrote {path}")


def print_export_commands() -> None:
    """Print shell export commands for direct poetry usage."""
    print("\nCopy-paste these into your shell (or add to ~/.zshrc for persistence):\n")
    for key, value in DEV_ENV.items():
        print(f"  export {key}={value!r}")
    print()


def verify_keycloak() -> bool:
    """Return True if the Keycloak JWKS endpoint is reachable."""
    url = DEV_ENV["AUTH_JWKS_URI"]
    try:
        with urllib.request.urlopen(url, timeout=5) as resp:
            if resp.status == 200:
                print(f"  Keycloak JWKS reachable at {url}")
                return True
    except Exception as exc:
        print(f"  Keycloak not reachable at {url}: {exc}", file=sys.stderr)
    return False


def get_token() -> str | None:
    """Request a token from Keycloak using password grant and return it."""
    token_url = DEV_ENV["AUTH_TOKEN_URL"]
    data = urllib.parse.urlencode(
        {
            "grant_type": "password",
            "client_id": DEV_ENV["AUTH_CLIENT_ID"],
            # No client_secret — howlermcp is a public client using PKCE.
            "username": _TEST_USER,
            "password": _TEST_PASS,
            "scope": DEV_ENV["MCP_SCOPE"],
        }
    ).encode()
    try:
        req = urllib.request.Request(token_url, data=data, method="POST")
        with urllib.request.urlopen(req, timeout=10) as resp:
            body = json.loads(resp.read())
            token = body.get("access_token")
            if token:
                print(f"  Fetched bearer token for user '{_TEST_USER}'")
                return token
            print(f"  No access_token in response: {body}", file=sys.stderr)
    except urllib.error.HTTPError as exc:
        print(
            f"  Token request failed ({exc.code}): {exc.read().decode()}",
            file=sys.stderr,
        )
    except Exception as exc:
        print(f"  Token request error: {exc}", file=sys.stderr)
    return None


def clear_port(port: int) -> None:
    """Stop any Docker container using the given port and kill any other process holding it."""
    print(f"\n3. Clearing port {port}:")

    # Stop any container whose name contains "howler-mcp" or "howler_mcp".
    # These are the containers started by docker compose from mcp/.
    try:
        result = subprocess.run(
            ["docker", "ps", "--format", "{{.Names}}"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        for name in result.stdout.splitlines():
            if "howler" in name and "mcp" in name:
                subprocess.run(
                    ["docker", "stop", name], capture_output=True, timeout=15
                )
                print(f"  Stopped container: {name}")
    except Exception as exc:
        print(f"  Could not query Docker containers: {exc}", file=sys.stderr)

    # Kill any remaining process holding the port (e.g. a poetry server).
    try:
        result = subprocess.run(
            ["lsof", "-ti", f":{port}"], capture_output=True, text=True, timeout=5
        )
        pids = [int(p) for p in result.stdout.split() if p.strip()]
        for pid in pids:
            try:
                os.kill(pid, signal.SIGTERM)
                print(f"  Killed process {pid} on port {port}")
            except ProcessLookupError:
                pass
    except Exception:
        pass

    # Last resort: fuser -k
    subprocess.run(["fuser", "-k", f"{port}/tcp"], capture_output=True)

    print(f"  Port {port} is free")


def update_mcp_json(token: str) -> None:
    """Update .vscode/mcp.json with the bearer token so VS Code can authenticate immediately."""
    mcp_json_path = Path(__file__).parent.parent.parent / ".vscode" / "mcp.json"

    config = {
        "servers": {
            "howlerMcp": {
                "url": "http://localhost:8000/mcp",
                "type": "http",
                "headers": {"Authorization": f"Bearer {token}"},
            }
        },
        "inputs": [],
    }

    mcp_json_path.write_text(json.dumps(config, indent=2))
    print(f"  Updated {mcp_json_path}")


def start_server(env_path: Path) -> None:
    """Source the .env file and start the server via poetry."""
    # Build env for the subprocess: current env + everything from .env.
    env = os.environ.copy()
    for line in env_path.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            key, _, value = line.partition("=")
            env[key.strip()] = value.strip()

    print("\n4. Starting MCP server (poetry):")
    print("   Press Ctrl+C to stop.\n")
    mcp_dir = env_path.parent
    subprocess.run(
        ["poetry", "run", "python", "-m", "howler_mcp.server"],
        cwd=mcp_dir,
        env=env,
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        help="Check that Keycloak is reachable after writing .env",
    )
    parser.add_argument(
        "--token",
        action="store_true",
        help="Write .env, verify Keycloak, fetch a token, and update .vscode/mcp.json",
    )
    parser.add_argument(
        "--start",
        action="store_true",
        help="Write .env, verify Keycloak, fetch token, update mcp.json, then start the server with poetry",
    )
    args = parser.parse_args()

    env_path = Path(__file__).parent.parent / ".env"

    print("\nHowler MCP — dev environment setup")
    print("=" * 40)

    print("\n1. Writing .env (picked up automatically by docker compose up):")
    write_env_file(env_path)

    print("\n2. Shell exports (for poetry run python -m howler_mcp.server):")
    print_export_commands()

    if args.verify or args.token or args.start:
        print("3. Verifying Keycloak connectivity:")
        ok = verify_keycloak()
        if not ok:
            print(
                "  Start dependencies first: docker compose up -d  (from api/dev/)",
                file=sys.stderr,
            )
            sys.exit(1)

    if args.token or args.start:
        print("4. Fetching test token and updating .vscode/mcp.json:")
        token = get_token()
        if token:
            update_mcp_json(token)
            print("  VS Code MCP client is now configured and ready to use.")
        else:
            print(
                "  Failed to fetch token. Check Keycloak logs.",
                file=sys.stderr,
            )
            sys.exit(1)

    if args.start:
        clear_port(int(DEV_ENV["MCP_PORT"]))
        start_server(env_path)
        return

    print("\nDone. To start the MCP server:\n")
    print("  # Option A — start both dependencies and server (recommended):")
    print("  python3 dev_setup.py --start\n")
    print("  # Option B — start dependencies and server separately:")
    print("  docker compose up -d  # (from api/dev/)")
    print("  poetry run python -m howler_mcp.server\n")


if __name__ == "__main__":
    main()
