"""Dev environment setup for the Howler MCP server.

Mirrors the purpose of api/howler/odm/random_data.py — a single script
that bootstraps everything needed for local development.

What it does:
  1. Writes a .env file. docker compose reads it automatically, and
     howler_mcp.config loads it via python-dotenv for direct/local runs.
  2. Optionally verifies that Keycloak is reachable.
  3. Optionally fetches a bearer token from Keycloak and injects it into
     .vscode/mcp.json so VS Code can authenticate immediately (no prompts).

Usage:
  python3 dev_setup.py              # write .env
  python3 dev_setup.py --verify     # also verify Keycloak connectivity
  python3 dev_setup.py --token      # also fetch token and update mcp.json
  python3 dev_setup.py --start      # do all above, then start the MCP server

Why the token is written literally into mcp.json:
  VS Code's "http" server type only accepts "headers"/"oauth" fields (no
  "env"/"envFile", which are stdio-only), and header values only expand
  "${input:...}" placeholders, not "${env:...}". So there is no supported way
  to point at an environment variable for this transport — a real value is
  required for a zero-prompt connection. Both generated files are gitignored
  and chmod'd to 0600 to limit the plaintext exposure.
"""

import argparse
import json
import os
import shutil
import signal
import subprocess
import sys
from pathlib import Path

import httpx

from howler_mcp.config import AUTH, MCPSettings

# Dev credentials for the token verification step.
_TEST_USER = "goose"
_TEST_PASS = "goose"

# Compose service name for the MCP server itself, used to scope port cleanup
# so we never touch unrelated containers on the host.
_MCP_SERVICE = "howler-mcp"
_KEYCLOAK_REALM_FILE = Path(__file__).parent.parent.parent / "api" / "dev" / "keycloak" / "keycloak-realm.json"


def _restrict_to_owner(path: Path) -> None:
    """Chmod a file to 0600 so only the current user can read secrets in it.

    Mitigates the plaintext-storage risk noted by static analysis (CWE-312):
    the file must hold a raw dev credential for VS Code/docker compose to use
    it, so access is restricted at the filesystem level instead.
    """
    try:
        os.chmod(path, 0o600)
    except OSError as exc:
        print(f"  Could not restrict permissions on {path}: {exc}", file=sys.stderr)


def _get_client_secret() -> str | None:
    """Return the configured dev client secret without exposing it in output."""
    if AUTH.CLIENT_SECRET:
        return AUTH.CLIENT_SECRET

    configured_secret = os.environ.get("AUTH_CLIENT_SECRET")
    if configured_secret:
        return configured_secret

    try:
        realm = json.loads(_KEYCLOAK_REALM_FILE.read_text())
        for client in realm.get("clients", []):
            if client.get("clientId") == AUTH.CLIENT_ID:
                return client.get("secret")
    except (OSError, json.JSONDecodeError) as e:
        print(f"Could not get client secret : {e}")

    return None


def write_env_file(path: Path) -> None:
    """Write the dev client secret to .env."""
    lines = ["# Auto-generated by dev_setup.py — DO NOT COMMIT\n"]
    client_secret = _get_client_secret()
    if client_secret:
        # lgtm[py/clear-text-storage-sensitive-data]: local dev-only credential, file is gitignored and locked down below.
        lines.append(f"AUTH_CLIENT_SECRET={client_secret}\n")
    path.write_text("".join(lines))
    _restrict_to_owner(path)
    print(f"  Wrote {path}")


def _find_executable(name: str) -> str | None:
    """Resolve an executable's absolute path on PATH.

    Used instead of passing bare command names to subprocess, so a malicious
    or unexpected executable earlier on PATH can't be run in its place.
    """
    return shutil.which(name)


def _confirm(prompt: str) -> bool:
    """Ask a yes/no question, defaulting to no on empty input, EOF, or Ctrl-C."""
    try:
        answer = input(f"{prompt} [y/N]: ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        print()
        return False
    return answer in ("y", "yes")


def verify_keycloak() -> bool:
    """Return True if the Keycloak JWKS endpoint is reachable."""
    if not AUTH.JWKS_URI.startswith(("http://", "https://")):
        print(f"  Refusing to open non-http(s) URL: {AUTH.JWKS_URI}", file=sys.stderr)
        return False

    try:
        httpx.get(AUTH.JWKS_URI, timeout=5).raise_for_status()
        print(f"  Keycloak JWKS reachable at {AUTH.JWKS_URI}")
        return True
    except httpx.HTTPError as e:
        print(f"  Keycloak not reachable at {AUTH.JWKS_URI}: {e}", file=sys.stderr)

    return False


def get_token() -> str | None:
    """Request a token from Keycloak using password grant and return it."""
    if not AUTH.TOKEN_URL.startswith(("http://", "https://")):
        print(f"  Refusing to open non-http(s) URL: {AUTH.TOKEN_URL}", file=sys.stderr)
        return None

    payload = {
        "grant_type": "password",
        "client_id": AUTH.CLIENT_ID,
        "username": _TEST_USER,
        "password": _TEST_PASS,
        "scope": MCPSettings.SCOPE,
    }

    client_secret = _get_client_secret()
    if client_secret:
        payload["client_secret"] = client_secret

    try:
        response = httpx.post(AUTH.TOKEN_URL, data=payload, timeout=10)
        response.raise_for_status()
        body = response.json()

        if body.get("access_token"):
            print(f"  Fetched bearer token for user '{_TEST_USER}'")
            return body.get("access_token")

        print(f"  No access_token in response: {body}", file=sys.stderr)
    except (httpx.HTTPError, json.JSONDecodeError) as e:
        print(f"  Token request error: {e}", file=sys.stderr)

    return None


def clear_port(port: int) -> None:
    """Stop the howler-mcp container (if running) and free the given port."""
    print(f"\n4. Clearing port {port}:")

    # Stop only the howler-mcp compose service, never any other container on
    # the host, even if its name happens to also contain "howler"/"mcp".
    # Could be made better if we really want to. But if we consider this for only dev it should be enough
    mcp_dir = Path(__file__).parent.parent

    docker = _find_executable("docker")
    if docker:
        try:
            result = subprocess.run(
                [docker, "compose", "--profile", "full", "ps", "--format", "{{.Service}}"],
                cwd=mcp_dir,
                capture_output=True,
                text=True,
                timeout=10,
            )
            if _MCP_SERVICE in result.stdout.split():
                subprocess.run(
                    [docker, "compose", "--profile", "full", "stop", _MCP_SERVICE],
                    cwd=mcp_dir,
                    capture_output=True,
                    timeout=15,
                )
                print(f"  Stopped the {_MCP_SERVICE} container")
        except Exception as exc:
            print(f"  Could not check/stop the {_MCP_SERVICE} container: {exc}", file=sys.stderr)

    # Kill any remaining process holding the port (e.g. a poetry server).
    lsof = _find_executable("lsof")
    if lsof:
        try:
            result = subprocess.run([lsof, "-ti", f":{port}"], capture_output=True, text=True, timeout=5)

            for pid in [int(p) for p in result.stdout.split() if p.strip()]:
                try:
                    os.kill(pid, signal.SIGTERM)
                    print(f"  Killed process {pid} on port {port}")
                except ProcessLookupError:
                    print(f"  Process {pid} exited before it could be stopped")

        except Exception as exc:
            print(f"  Could not inspect port {port} with lsof: {exc}", file=sys.stderr)

    # Last resort: fuser -k
    fuser = _find_executable("fuser")
    if fuser:
        subprocess.run([fuser, "-k", f"{port}/tcp"], capture_output=True)

    print(f"  Port {port} is free")


def update_mcp_json(token: str, mcp_json_path: Path | None = None) -> None:
    """Update .vscode/mcp.json with the bearer token, preserving any other existing content."""
    if not mcp_json_path:
        mcp_json_path = Path(__file__).parent.parent.parent / ".vscode" / "mcp.json"

    mcp_json_path.parent.mkdir(parents=True, exist_ok=True)

    config: dict = {}
    if mcp_json_path.exists():
        try:
            config = json.loads(mcp_json_path.read_text())
        except json.JSONDecodeError:
            config = {}

    config.setdefault("servers", {})
    config.setdefault("inputs", [])
    config["servers"]["howlerMcp"] = {
        "url": MCPSettings.BASE_URL,
        "type": "http",
        # lgtm[py/clear-text-storage-sensitive-data]: short-lived local dev token, file is gitignored and locked down below.
        "headers": {"Authorization": f"Bearer {token}"},
    }

    mcp_json_path.write_text(json.dumps(config, indent=2))
    _restrict_to_owner(mcp_json_path)
    print(f"  Updated {mcp_json_path}")


def start_server(env_path: Path) -> None:
    """Start the MCP server via poetry; howler_mcp.config loads env_path's .env itself."""
    print("\n5. Starting MCP server:")
    print("\tPress Ctrl+C to stop.\n")
    mcp_dir = env_path.parent
    print(f"\tUsing interpreter: {sys.executable}")
    print(f"\tWorking directory: {mcp_dir}")
    subprocess.run(
        [sys.executable, "-m", "howler_mcp.server"],
        cwd=mcp_dir,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--verify",
        action="store_true",
        help="Check that Keycloak is reachable after writing .env",
    )
    parser.add_argument(
        "--token",
        action="store_true",
        help="Write .env, verify Keycloak, fetch a token, and update .vscode/mcp.json",
    )
    parser.add_argument(
        "--start",
        action="store_true",
        help="Write .env, verify Keycloak, fetch token, update mcp.json, then start the server with poetry",
    )
    parser.add_argument(
        "-y",
        "--yes",
        action="store_true",
        help="Assume yes to the port-clearing confirmation prompt (non-interactive use)",
    )
    args = parser.parse_args()

    env_path = Path(__file__).parent.parent / ".env"

    print("\nHowler MCP — dev environment setup")
    print("=" * 40)

    print("\n1. Writing .env (loaded by docker compose, and by howler_mcp.config via python-dotenv):")
    write_env_file(env_path)

    if args.verify or args.token or args.start:
        print("2. Verifying Keycloak connectivity:")
        ok = verify_keycloak()
        if not ok:
            print(
                "  Start dependencies first: docker compose up -d  (from api/dev/)",
                file=sys.stderr,
            )
            sys.exit(1)

    if args.token or args.start:
        print("3. Fetching test token and updating .vscode/mcp.json:")
        token = get_token()
        if token:
            update_mcp_json(token)
            print("  VS Code MCP client is now configured and ready to use.")
        else:
            print(
                "  Failed to fetch token. Check Keycloak logs.",
                file=sys.stderr,
            )
            sys.exit(1)

    if args.start:
        if args.yes or _confirm(f"Stop any process/container using port {MCPSettings.PORT} to free it?"):
            clear_port(int(MCPSettings.PORT))

        start_server(env_path)
        return

    print("\nDone. To start the MCP server:\n")
    print("  # Option A — start both dependencies and server (recommended):")
    print("  python3 dev_setup.py --start\n")
    print("  # Option B — start dependencies and server separately:")
    print("  docker compose up -d  # (from api/dev/)")
    print("  poetry run python -m howler_mcp.server\n")


if __name__ == "__main__":
    main()
