import pyspark.sql.types as T  # noqa: N812
from howler.odm import (
    IP,
    MAC,
    MD5,
    SHA1,
    SHA256,
    URI,
    UUID,
    Any,
    Boolean,
    CaseInsensitiveKeyword,
    Classification,
    ClassificationString,
    Date,
    Domain,
    Email,
    Enum,
    FlattenedObject,
    Float,
    HowlerHash,
    Integer,
    Json,
    Keyword,
    Long,
    LowerKeyword,
    PhoneNumber,
    Platform,
    Processor,
    SSDeepHash,
    Text,
    UpperKeyword,
    URIPath,
    ValidatedKeyword,
)

# Simple types can be resolved by a direct mapping
BASE_TYPE_MAPPING = {
    Keyword: T.StringType(),
    Boolean: T.BooleanType(),
    Integer: T.IntegerType(),
    Long: T.LongType(),
    Float: T.DoubleType(),
    Date: T.TimestampType(),
    Text: T.StringType(),
    Classification: T.StringType(),
    ClassificationString: T.StringType(),
    Enum: T.StringType(),
    UUID: T.StringType(),
    IP: T.StringType(),  # TODO we need to think about how to represent IP addresses (bytes all?)
    Domain: T.StringType(),
    Email: T.StringType(),
    URI: T.StringType(),
    URIPath: T.StringType(),
    MAC: T.StringType(),
    PhoneNumber: T.StringType(),
    SSDeepHash: T.StringType(),
    SHA1: T.StringType(),
    SHA256: T.StringType(),
    HowlerHash: T.StringType(),
    MD5: T.StringType(),
    Platform: T.StringType(),
    Processor: T.StringType(),
    FlattenedObject: T.StringType(),  # like an object as json string, won't parse out into struct for sync
    Any: T.StringType(),
    UpperKeyword: T.StringType(),
    LowerKeyword: T.StringType(),
    Json: T.StringType(),
    ValidatedKeyword: T.StringType(),
    CaseInsensitiveKeyword: T.StringType(),
}

TYPE_MAPPING: dict[str, T.DataType] = {_class.__name__: mapping for _class, mapping in BASE_TYPE_MAPPING.items()}
