"""Spark types for the canonical Howler field metadata kinds."""

import pyspark.sql.types as T  # noqa: N812

TYPE_MAPPING: dict[str, T.DataType] = {
    "Keyword": T.StringType(),
    "Boolean": T.BooleanType(),
    "Integer": T.IntegerType(),
    "Long": T.LongType(),
    "Float": T.DoubleType(),
    "Date": T.TimestampType(),
    "Text": T.StringType(),
    "Classification": T.StringType(),
    "ClassificationString": T.StringType(),
    "Enum": T.StringType(),
    "UUID": T.StringType(),
    "IP": T.BinaryType(),  # variable-length bytes hold both IPv4 and IPv6
    "Domain": T.StringType(),
    "Email": T.StringType(),
    "URI": T.StringType(),
    "URIPath": T.StringType(),
    "MAC": T.StringType(),
    "PhoneNumber": T.StringType(),
    "SSDeepHash": T.StringType(),
    "SHA1": T.StringType(),
    "SHA256": T.StringType(),
    "HowlerHash": T.StringType(),
    "MD5": T.StringType(),
    "Platform": T.StringType(),
    "Processor": T.StringType(),
    "FlattenedObject": T.StringType(),
    "FlattenedListObject": T.StringType(),
    "Any": T.StringType(),
    "UpperKeyword": T.StringType(),
    "LowerKeyword": T.StringType(),
    "Json": T.StringType(),
    "ValidatedKeyword": T.StringType(),
    "CaseInsensitiveKeyword": T.StringType(),
    "EmptyableKeyword": T.StringType(),
}
