trigger:
  branches:
    include:
      - main
      - develop
      - rc/*
      - patch/*

pr:
  branches:
    include:
      - main
      - develop
      - rc/*
      - patch/*

variables:
  containerRegistry: 'uchimera'
  buildId: '$(Build.BuildId)'
  branch: '$(Build.SourceBranchName)'
  isDevelop: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]
  repoName: 'howler-ui'
  isPrBranch: $[eq(variables['Build.SourceBranchName'], 'merge')]

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: BuildAndTestSource
        displayName: Build And Test Source
        steps:
          - script: |
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
              nvm install v20
            displayName: 'Nvm'
          - script: |
              npm install -g corepack@latest
              corepack enable pnpm
              pnpm setup
              pnpm install --frozen-lockfile
            displayName: 'pnpm install'
          - script: |
              npx eslint src
            displayName: 'Eslint checks'
          - script: |
              npx prettier@^3.2.5 -c src
            displayName: 'Prettier checks'
          - script: |
              export VITE_BRANCH=$(branch)
              export VITE_COMMIT_HASH=$(Build.SourceVersion)
              export NODE_OPTIONS=--max-old-space-size=16384
              pnpm run build
            displayName: 'Vite build'
