allowBuilds:
  '@firebase/util': true
  '@swc/core': true
  esbuild: true
  msw: true
  protobufjs: true
  rxdb: true
  unrs-resolver: true

minimumReleaseAge: 1440

overrides:
  handlebars-async-helpers>handlebars: '4.*'
